#!/bin/bash
sudo docker run --name mysql-server -e MYSQL_ROOT_PASSWORD=1234 -d mysql
sudo docker run --name phpmyadmin -d --link mysql-server:db -p 8080:80 phpmyadmin
containerId=`sudo docker ps -aqf "name=mysql"`
sudo docker cp DB/dbScript.sql $containerId:/dbScript.sql
sudo docker exec -it $containerId /bin/bash
mysql -uroot -p1234 mysql < dbScript.sql
exit
