#!/bin/bash
sudo docker run --name mysql-server -e MYSQL_ROOT_PASSWORD=1234 -d mysql
sudo docker run --name phpmyadmin -d --link mysql-server:db -p 8080:80 phpmyadmin
containerId=`sudo docker ps -aqf "name=mysql"`
#sudo docker cp DB/dbScript.sql $containerId:/dbScript.sql
sudo docker exec -i $containerId mysql -uroot -p1234 mysql < DB/dbScript.sql
sudo docker exec -i $containerId echo "bind-address            =  127.0.0.1" >> /etc/mysql/conf.d/mysql.cnf
