#!/bin/bash
RED=`tput setaf 1`
GREEN=`tput setaf 2`
NC=`tput sgr0`

/bin/bash ./getIP

echo -e "\n${GREEN}Installing OpenJDK 11${NC}\n"
sudo apt install openjdk-11-jdk openjdk-11-jre

echo -e "\n${GREEN}Installing Maven${NC}\n"
sudo apt install maven

echo -e "\n${GREEN}Deploying Backend  Server${NC}\n"
/bin/bash ./deployBackend

echo -e "\n${GREEN}Deploying Frontend Server${NC}\n"
/bin/bash ./deployFrontend

echo -e "\n${GREEN}Deploying Database${NC}\n"
/bin/bash ./deployDB

#echo -e "\n${GREEN}Configuring Firewall${NC}\n"
#/bin/bash ./configureFirewall

#echo -e "\n${GREEN}Setup Autoscaling${NC}\n"
#/bin/bash ./autoScale
