#!/bin/bash
RED=`tput setaf 1`
GREEN=`tput setaf 2`
NC=`tput sgr0`

echo -e "\n${GREEN}Deploying Backend  Server${NC}\n"
/bin/bash ./deployBackend

echo -e "\n${GREEN}Deploying Frontend Server${NC}\n"
/bin/bash ./deployFrontend

echo -e "\n${GREEN}Deploying Database${NC}\n"
